import { useLocalSearchParams } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { fetchClubSession, type ClubSessionDetail } from '../../../src/lib/api';
import { useDisplayFont } from '../../../src/lib/displayFont';
import { useNumFont } from '../../../src/lib/fonts';
import { getNaverMap, subscribePack, type LiveLinkState } from '../../../src/lib/geo';
import { goBackOrHome } from '../../../src/lib/nav';
import {
  agoLabel, mergePeer, packCamera, parsePackPos, peerAge, visiblePeers,
  type PackCamera, type PackPeer,
} from '../../../src/lib/pack';
import { useMyProfileId, usePackShare } from '../../../src/lib/use-pack-share';
import { paper } from '../../../src/theme';

// 팩 지도 — one club session, everybody on it, a little runner icon each.
//
// ═══ THE RULING ════════════════════════════════════════════════════════════════════════════════
// Sean, 2026-08-28, verbatim: 「everyone should see everyone else on the map during a club run
// session with a little runner icon. total public; everything that's not their password is public
// to anyone.」 Asked whether to wait for counsel, he answered 「Build it now anyway」 and 「forget
// about all legal concerns」. Both rounds are in `docs/decisions/2026-08-28-sean-rulings.md`.
// **The privacy question was put to him and overruled; no session re-opens it.** Phones stay
// host-only — that ruling was NOT widened (`password-scope`, same document).
//
// ═══ THE LAYOUT IS A PICKED MOCK, NOT AN INVENTION ═════════════════════════════════════════════
// `docs/labs/club-v2-livemap-lab.html` frame ① (Sean, round 7: 「i like all lab screens」) is a
// full-bleed map under a white mastchip (‹ · display name · live dot) with a bottom paper strip:
// a numeral hero row over an ink 1.5px rule and a crew line.
//
// ⚠ WHAT IS DELIBERATELY *NOT* COPIED FROM IT, and why each omission is the honest move:
//   · The mock is the HOST's view. Its three exits (페어 목록 · 케이스 등록 · 비상 도구) and its
//     thumb CTA (러닝 종료) are host supervision powers that live on the console and run screens.
//     Rendering them here would be dead buttons — an action with no effect in this state.
//   · The mock's numeral row has THREE cells (경과 · 러닝 중 · 케이스). **Only 러닝 중 can be
//     bound to a real field from this screen.** `club_session_detail` carries the SCHEDULED time,
//     not an actual pack start, so 경과 computed here would be a fabricated number that inflates
//     whenever a session starts late; and the case count is the console's data. Two invented
//     numerals to match a mock is exactly the trade this repo refuses — so one cell renders and
//     the gap is reported rather than papered over.
//
// ═══ WHAT IS DRAWN, AND WHAT IS REFUSED ════════════════════════════════════════════════════════
// Markers come from the CHANNEL, never from the roster. The roster says who MIGHT run; only a
// broadcast says where somebody IS. So a member who has not started is absent rather than pinned
// at a guess, `(0,0)` and far-future stamps are refused by the parser, and a fix older than
// PACK_STALE_MS is removed instead of aged into a lie. Every kind of participant is drawn the
// same way — a 동반 owner walking their own dog and a delegated runner are one population here,
// which is what 「everyone should see everyone else」 means.
//
// ⚠ AND ONE GAP THAT IS REAL TODAY, said here because the map cannot show it: publishing lives in
// `usePackShare`, called from this screen and from `club/companion/[sid].tsx`. `club/run/[sid].tsx`
// — the delegated runner's screen — is held by another session tonight and does NOT call it yet,
// so a delegated runner appears here only while they have this screen open. It is one line wide
// and it is reported to the coordinator.
//
// PAPER WORLD (DESIGN.md §2/§4): white canvas · square corners · detail floor 15pt · Black Han
// Sans once per screen (the mastchip title) · Oswald numerals with an explicit lineHeight ≥1.2×.

const MAP_ASSETS = {
  // Generated by `scripts/gen-pack-runner-icon.mjs` (reviewable as geometry, not opaque bytes).
  // A `require`d PNG is the ONE Naver marker path this repo has shipped and seen on a device
  // (`route-anchor.png`, owner/live.tsx). The custom-React-view marker type is documented as a
  // performance hazard and needs `collapsable={false}` on iOS's new architecture — an untested
  // path, and this screen is not device-verified.
  other: require('../../../assets/pack-runner.png'),
  me: require('../../../assets/pack-runner-me.png'),
};

// Marker box. Not tappable, deliberately: **Naver markers have no hit-slop** (measured in this
// repo), so a tappable marker gets either an oversized invisible target that swallows map pans or
// a target nobody can hit. The name is already on the caption and there is nothing a tap would do.
const MARKER_PT = 32;

// The freshness clock. Markers only change when a broadcast ARRIVES, so without a tick a peer who
// went silent would keep looking current forever — the frozen-countdown defect, on a map.
const AGE_TICK_MS = 5_000;

type Load = 'loading' | 'ready' | 'missing' | 'error';

export default function ClubPackMap() {
  const { sid, clubName } = useLocalSearchParams<{ sid: string; clubName?: string }>();
  const sessionId = String(sid ?? '');
  const disp = useDisplayFont();
  const nf = useNumFont();

  const maps = getNaverMap();

  const [detail, setDetail] = useState<ClubSessionDetail | null>(null);
  const [load, setLoad] = useState<Load>('loading');
  const [link, setLink] = useState<LiveLinkState>('connecting');
  const [peers, setPeers] = useState<Map<string, PackPeer>>(() => new Map());
  const [now, setNow] = useState(() => Date.now());

  // Publishing is the hook's job, not this screen's — see the block comment in use-pack-share.ts
  // for why it cannot live here alone.
  const sharing = usePackShare(sessionId || null, detail);
  // The local user's own id, so their marker can be told from a stranger's. Shared with the hook
  // so one screen makes one `getUser` call, and so 「who am I」 has a single definition.
  const myId = useMyProfileId();

  // `fetchClubSession` and NOT `fetchSessionRoster`: the roster RPC writes a phone-view audit row
  // for every member whose number it returns (0053), on a screen that renders no numbers. A false
  // audit trail is worse than a missing convenience — the finding that shaped club/companion.
  const loadSession = useCallback(() => {
    if (!sessionId) { setLoad('missing'); return; }
    setLoad('loading');
    fetchClubSession(sessionId)
      .then((d) => { setDetail(d); setLoad(d ? 'ready' : 'missing'); })
      .catch(() => { setDetail(null); setLoad('error'); });
  }, [sessionId]);
  useEffect(loadSession, [loadSession]);

  // Subscribe ALWAYS, per the contract: reads are public and the subscribe carries no gate, so
  // this runs whether or not the local user is running, checked in, or a member at all.
  useEffect(() => {
    if (!sessionId) return;
    return subscribePack(sessionId, (raw) => {
      const p = parsePackPos(raw);
      if (!p) return;                        // malformed, out of range, Null Island, or far-future
      setPeers((cur) => mergePeer(cur, p));  // returns the SAME map when nothing moved
    }, setLink);
  }, [sessionId]);

  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), AGE_TICK_MS);
    return () => clearInterval(t);
  }, []);

  const shown = useMemo(() => visiblePeers(peers, now), [peers, now]);

  // The camera is taken on the FIRST frame that has one and then HELD, so an incoming position
  // does not yank the view out from under a finger mid-pan.
  // ⚠ State, not a ref. A ref written and read in the same render works only by luck of ordering,
  // and `react-hooks/refs` flags every read — the value genuinely IS needed for rendering, which
  // is the definition of state.
  const [camera, setCamera] = useState<PackCamera | null>(null);
  useEffect(() => {
    if (camera !== null) return;
    const c = packCamera(shown);
    if (c) setCamera(c);
  }, [shown, camera]);

  const mapReady = !!maps && !!camera && shown.length > 0;
  // ⚠ 「loading is not 0」. Before the channel has joined we have not measured anything, and a 0
  // here would assert an empty pack we have not observed.
  const measured = link !== 'connecting' && load !== 'loading';

  const shareLine = sharing === null
    ? '내 위치 확인 중...'
    : sharing
      ? '내 위치 공유 중'
      : detail?.myAttendance === 'checked_in'
        ? '내 위치 잡히는 중'
        : '보기만 하는 중';

  return (
    <View style={s.root}>
      <StatusBar style="dark" />

      {mapReady && maps && camera ? (
        <maps.NaverMapView
          style={StyleSheet.absoluteFill}
          camera={camera}
          isShowLocationButton={false}
          isShowCompass={false}
          isShowScaleBar={false}
          isShowZoomControls={false}
        >
          {shown.map((p) => {
            const stale = peerAge(p.atMs, now) === 'stale';
            const isMe = myId != null && p.profileId === myId;
            return (
              <maps.NaverMapMarkerOverlay
                key={p.profileId}
                latitude={p.lat}
                longitude={p.lng}
                anchor={{ x: 0.5, y: 0.5 }}
                width={MARKER_PT}
                height={MARKER_PT}
                image={isMe ? MAP_ASSETS.me : MAP_ASSETS.other}
                // A stale marker is drawn faintly and says how old it is. Drawing it at full
                // strength would be the map asserting a position it does not have.
                alpha={stale ? 0.45 : 1}
                caption={{
                  text: stale ? `${p.name} · ${agoLabel(p.atMs, now)}` : p.name,
                  textSize: 15,
                  color: paper.ink,
                  haloColor: '#FFFFFF',
                }}
                zIndex={isMe ? 3 : 2}
              />
            );
          })}
        </maps.NaverMapView>
      ) : (
        /* An empty map draws five different facts identically. Each one says its own cause, or
           every one of them reads to the customer as 「nobody is running」. */
        <View style={s.emptyWrap}>
          {load === 'error' ? (
            <>
              <Text style={s.emptyTitle}>세션을 확인하지 못했어요</Text>
              <Pressable
                onPress={loadSession}
                hitSlop={12}
                accessibilityRole="button"
                accessibilityLabel="다시 시도"
                style={({ pressed }) => [s.retryBtn, pressed && s.retryBtnPressed]}
              >
                <Text style={s.retryTxt}>다시 시도</Text>
              </Pressable>
            </>
          ) : load === 'missing' ? (
            <Text style={s.emptyTitle}>이 세션을 찾을 수 없어요</Text>
          ) : !maps ? (
            <>
              <Text style={s.emptyTitle}>이 빌드에는 지도가 없어요</Text>
              <Text style={s.emptyBody}>새 빌드에서 팩 지도를 볼 수 있어요</Text>
            </>
          ) : link === 'denied' ? (
            <>
              <Text style={s.emptyTitle}>팩 지도에 연결할 수 없어요</Text>
              <Text style={s.emptyBody}>이 세션의 실시간 위치를 받을 권한이 없어요</Text>
            </>
          ) : link === 'error' ? (
            <>
              <Text style={s.emptyTitle}>실시간 위치에 연결하지 못했어요</Text>
              <Text style={s.emptyBody}>네트워크를 확인해주세요 — 러닝과 기록은 그대로 진행돼요</Text>
            </>
          ) : !measured ? (
            <Text style={s.emptyTitle}>연결하는 중...</Text>
          ) : (
            <>
              <Text style={s.emptyTitle}>아직 아무도 달리고 있지 않아요</Text>
              <Text style={s.emptyBody}>러닝이 시작되면 여기에 나타나요</Text>
            </>
          )}
        </View>
      )}

      {/* ---------- 마스트칩 (lab ①) — ‹ · 이름 · 라이브 도트를 한 판에 ---------- */}
      <View style={s.mastchip}>
        <Pressable
          onPress={goBackOrHome}
          style={s.back}
          accessibilityRole="button"
          accessibilityLabel="뒤로"
        >
          <Text style={s.backGlyph}>‹</Text>
        </Pressable>
        <Text style={[s.disp, disp]} numberOfLines={1}>{clubName ? String(clubName) : '팩 지도'}</Text>
        {/* The dot is a claim that the channel is joined — it is bound to the link state, never
            drawn decoratively. Honest motion law: no idle pulse, no fake liveness. */}
        {link === 'live' && <View style={s.livedot} />}
      </View>

      {/* ---------- 스트립 (lab ①) — 실측 가능한 숫자 하나 + 크루 줄 ---------- */}
      <View style={s.strip}>
        <View style={s.nums}>
          <View style={s.numCell}>
            <Text style={[s.numV, nf]}>{measured ? String(shown.length) : '—'}</Text>
            <Text style={s.numL}>지도에 표시 중</Text>
          </View>
        </View>
        <View style={s.crew}>
          <Text style={s.crewT}>{shareLine}</Text>
          {!!detail?.meetupPoint && (
            <Text style={s.crewOthers} numberOfLines={1}>{detail.meetupPoint}</Text>
          )}
        </View>
      </View>
    </View>
  );
}

// Values are lab ①'s, converted one-for-one: mastchip 16/44 · pad 10/14 · gap 11 · back 34 with a
// 1px #C2BFB7 border and a 24pt glyph · disp 24/30 Black Han Sans · livedot 10 round coral ·
// strip 16/16 · numeral hero 38/48 Oswald · label 15/21 700 dim · crew rule 1.5px ink.
const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: paper.canvas },

  mastchip: {
    position: 'absolute', top: 44, left: 16, zIndex: 2,
    flexDirection: 'row', alignItems: 'center', gap: 11,
    backgroundColor: paper.canvas, paddingVertical: 10, paddingHorizontal: 14, maxWidth: '86%',
  },
  back: {
    width: 34, height: 34,
    borderWidth: 1, borderColor: '#C2BFB7', backgroundColor: paper.canvas,
    alignItems: 'center', justifyContent: 'center',
  },
  backGlyph: { fontSize: 24, lineHeight: 28, color: paper.ink },
  // Black Han Sans, once per screen (DESIGN.md §3 budget). This is that one use.
  disp: { fontSize: 24, lineHeight: 30, color: paper.ink, letterSpacing: -0.24, flexShrink: 1 },
  livedot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#F0765A' },

  // 빈 지도면 — 다섯 갈래가 각자 자기 원인을 말한다 (전부 '빈 지도'로 보이기 때문이다).
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  emptyTitle: { fontSize: 16, fontWeight: '900', color: paper.ink, textAlign: 'center' },
  // §7a-bis: 행동에 필요한 문장은 딤이 아니라 잉크. 이 화면의 본문은 이 한 줄이 전부다.
  emptyBody: { fontSize: 15, color: paper.text, marginTop: 6, textAlign: 'center', lineHeight: 19.5 },
  // 세컨더리 버튼 매트릭스(F2.1): 캔버스 면 + 코랄 1px + actionInk 라벨, pressed는 wash.
  // 면이 없는 버튼이라 §3b는 scale(0.96)을 주지만 여기선 44pt 타깃이 우선이라 패딩으로 크기를
  // 확보하고 눌림은 색으로 말한다 (오퍼시티 금지 — 매트릭스 법).
  retryBtn: {
    marginTop: 14, paddingVertical: 12, paddingHorizontal: 22,
    backgroundColor: paper.canvas, borderWidth: 1, borderColor: paper.line,
  },
  retryBtnPressed: { backgroundColor: paper.wash },
  retryTxt: { fontSize: 16, fontWeight: '800', color: paper.actionInk },

  strip: {
    position: 'absolute', left: 16, right: 16, bottom: 40, zIndex: 2,
    backgroundColor: paper.canvas, paddingTop: 4,
  },
  nums: { flexDirection: 'row', alignItems: 'stretch' },
  numCell: { flex: 1, paddingTop: 16, paddingBottom: 14, paddingHorizontal: 8, alignItems: 'center' },
  // Oswald clips without an explicit lineHeight >= 1.2x — DESIGN.md "BUG A". 38/48 = 1.26x.
  numV: { fontSize: 38, lineHeight: 48, color: paper.ink },
  numL: { fontSize: 15, lineHeight: 21, fontWeight: '700', color: paper.dim, marginTop: 4 },
  crew: {
    flexDirection: 'row', alignItems: 'center', gap: 11,
    borderTopWidth: 1.5, borderTopColor: paper.ink,
    marginHorizontal: 14, paddingTop: 14, paddingBottom: 15,
  },
  // 딤이 아니라 잉크: 이 줄은 「내 위치가 지금 공개되고 있는가」를 말하는 유일한 자리이고,
  // 그건 건너뛰어도 되는 정보가 아니다 (§7a-bis — 딤은 건너뛰어도 되는 것에만).
  crewT: { fontSize: 15, lineHeight: 21, fontWeight: '800', color: paper.ink },
  crewOthers: { fontSize: 15, lineHeight: 21, fontWeight: '700', color: paper.dim, marginLeft: 'auto', flexShrink: 1 },
});
